### ISSUE TITLE
Implement health checking protocol

### ISSUE THREAD

**Issue by SProst** [cjihrig/grpc-server-js#3]
https://github.com/grpc/grpc/blob/master/doc/health-checking.md 

There appears to be support for this protocol in the various language bindings to GRPC. It might make sense to include it with this implementation.

**Comment by cjihrig** [comment]
So I haven't looked at the existing package in a ton of detail, but are you basically looking for https://github.com/grpc/grpc-node/tree/master/packages/grpc-health-check, but using the pure JS implementation instead of the `grpc` module? If so, I think we should try to work with the gRPC team to get support added there since it's just a service, and not functionality built into the server itself. If the gRPC team doesn't want to support pure JS in that module, we can fork it.

**Comment by cjihrig** [comment]
Note: As of [grpc-tools@1.8.0](https://github.com/grpc/grpc-node/releases/tag/grpc-tools@1.8.0), that module can generate code that works with `grpc` or `grpc-js`. I'm hoping the gRPC team will generate a new version of the health-check package, and that the `grpc-js` compatibility will work with this server as well. I'll have to investigate more.

**Comment by cjihrig** [comment]
OK, it looks like there is a plan in https://github.com/grpc/grpc-node/issues/926. Since this shouldn't require any action in this repo, I'm going to close this.
