### ISSUE TITLE
Support for hapi?

### ISSUE THREAD

**Issue by burgerboydaddy** [cjihrig/grpc-server-js#5]
Hello,
this is not an issue in the first place. Just question did you managed to integrate (create) gRPC server using hapi?
I watched your video from Node+JS Interactive, and you mentioned hapi a few times. Any success integrating with it?
Thanks in advance

**Comment by cjihrig** [comment]
If I'm remembering that talk correctly, I think I was talking about using hapi as a proxy for gRPC-Web. Is that what you're referring to?

**Comment by burgerboydaddy** [comment]
No, I'm interested in is it possible to use gRPC inside hapi?
Right now, I'm even not sure is that a good idea at all.

**Comment by cjihrig** [comment]
I'm not sure what the state of the art in hapi is regarding http2 support. Beyond that, gRPC adds its own protocol on top of http2. I think it *could* be done with some limitations, but I don't know that it would be worth it.

**Comment by burgerboydaddy** [comment]
I agree, after reviewing I found it is much better to keep them separated.
Thanks for answers. I will close this ticket (question).

**Comment by devinivy** [comment]
For what it's worth, hapi is a solid framework for writing applications in general, and just because you're not using hapi's HTTP listener doesn't mean you can't write a gRPC application on top of hapi!  Consider checking-out nes (websockets), lalalambda (serverless functions), susie (eventstreams), and underdog (http2 with push) for examples of how alternate transports can be supported via hapi.  The most relevant in this case are likely nes and lalalambda.

**Comment by cjihrig** [comment]
I did know that you could pass in a custom listener, but I had a couple concerns around that:

- One gRPC server can listen on multiple Node http/2 servers. I'm assuming we'd have to limit it to one http/2 server to integrate with hapi.
- What would the routing to gRPC handlers look like? Currently, [this](https://github.com/cjihrig/grpc-server-js/blob/3f9ca6f24af0b7d1bb7cd87216338ff1b6645b4e/lib/server.js#L316-L317) is the extent of the router required for gRPC itself.
- Would using a gRPC http/2 server impact routing for other plugins at all? If I were going to integrate gRPC with hapi, I'd only want to do so if I could use gRPC within a larger application. Otherwise, why not just use gRPC directly on its own.
- Kind of a meta-issue, but worth calling out: a hapi plugin would need to exist in a separate repo from this one.

I'm willing to work with anyone that interested in making this happen.

**Comment by devinivy** [comment]
I was actually meaning/trying to advocate for _not_ using hapi's listener, and instead creating your own special gRPC listener then tying it to the hapi server's lifecycle.  That would mean not using hapi routes, instead creating some new server decoration for registering handlers.  I am not familiar enough with gRPC to know if all those routing concepts have natural analogs to gRPC.

**Comment by cjihrig** [comment]
> just because you're not using hapi's HTTP listener

Sorry, I totally misinterpreted that as "you're not using hapi's HTTP listener because you're providing your own" 😊
